#!/usr/bin/env php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');
require dirname(__DIR__, 2) . '/vendor/autoload.php';
require dirname(__DIR__, 2) . '/vendor/yiisoft/yii2/Yii.php';

Yii::setAlias('@tests', dirname(__DIR__));
Yii::setAlias('@app', __DIR__);
$config = require(__DIR__ . '/config/console.php');
$app = new yii\console\Application($config);
$exitCode = $app->run();
exit($exitCode);
